// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: proto/codemakerai.proto

package stub

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CodemakerServiceClient is the client API for CodemakerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CodemakerServiceClient interface {
	AssistantCompletion(ctx context.Context, in *AssistantCompletionRequest, opts ...grpc.CallOption) (*AssistantCompletionResponse, error)
	AssistantCodeCompletion(ctx context.Context, in *AssistantCodeCompletionRequest, opts ...grpc.CallOption) (*AssistantCodeCompletionResponse, error)
	Completion(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error)
	Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error)
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error)
	DiscoverContext(ctx context.Context, in *DiscoverSourceContextRequest, opts ...grpc.CallOption) (*DiscoverSourceContextResponse, error)
	CreateContext(ctx context.Context, in *CreateSourceContextRequest, opts ...grpc.CallOption) (*CreateSourceContextResponse, error)
	RegisterContext(ctx context.Context, in *RegisterSourceContextRequest, opts ...grpc.CallOption) (*RegisterSourceContextResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
}

type codemakerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCodemakerServiceClient(cc grpc.ClientConnInterface) CodemakerServiceClient {
	return &codemakerServiceClient{cc}
}

func (c *codemakerServiceClient) AssistantCompletion(ctx context.Context, in *AssistantCompletionRequest, opts ...grpc.CallOption) (*AssistantCompletionResponse, error) {
	out := new(AssistantCompletionResponse)
	err := c.cc.Invoke(ctx, "/ai.codemaker.service.CodemakerService/AssistantCompletion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codemakerServiceClient) AssistantCodeCompletion(ctx context.Context, in *AssistantCodeCompletionRequest, opts ...grpc.CallOption) (*AssistantCodeCompletionResponse, error) {
	out := new(AssistantCodeCompletionResponse)
	err := c.cc.Invoke(ctx, "/ai.codemaker.service.CodemakerService/AssistantCodeCompletion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codemakerServiceClient) Completion(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error) {
	out := new(CompletionResponse)
	err := c.cc.Invoke(ctx, "/ai.codemaker.service.CodemakerService/Completion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codemakerServiceClient) Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error) {
	out := new(ProcessResponse)
	err := c.cc.Invoke(ctx, "/ai.codemaker.service.CodemakerService/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codemakerServiceClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, "/ai.codemaker.service.CodemakerService/Predict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codemakerServiceClient) DiscoverContext(ctx context.Context, in *DiscoverSourceContextRequest, opts ...grpc.CallOption) (*DiscoverSourceContextResponse, error) {
	out := new(DiscoverSourceContextResponse)
	err := c.cc.Invoke(ctx, "/ai.codemaker.service.CodemakerService/DiscoverContext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codemakerServiceClient) CreateContext(ctx context.Context, in *CreateSourceContextRequest, opts ...grpc.CallOption) (*CreateSourceContextResponse, error) {
	out := new(CreateSourceContextResponse)
	err := c.cc.Invoke(ctx, "/ai.codemaker.service.CodemakerService/CreateContext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codemakerServiceClient) RegisterContext(ctx context.Context, in *RegisterSourceContextRequest, opts ...grpc.CallOption) (*RegisterSourceContextResponse, error) {
	out := new(RegisterSourceContextResponse)
	err := c.cc.Invoke(ctx, "/ai.codemaker.service.CodemakerService/RegisterContext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codemakerServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, "/ai.codemaker.service.CodemakerService/ListModels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodemakerServiceServer is the server API for CodemakerService service.
// All implementations must embed UnimplementedCodemakerServiceServer
// for forward compatibility
type CodemakerServiceServer interface {
	AssistantCompletion(context.Context, *AssistantCompletionRequest) (*AssistantCompletionResponse, error)
	AssistantCodeCompletion(context.Context, *AssistantCodeCompletionRequest) (*AssistantCodeCompletionResponse, error)
	Completion(context.Context, *CompletionRequest) (*CompletionResponse, error)
	Process(context.Context, *ProcessRequest) (*ProcessResponse, error)
	Predict(context.Context, *PredictRequest) (*PredictResponse, error)
	DiscoverContext(context.Context, *DiscoverSourceContextRequest) (*DiscoverSourceContextResponse, error)
	CreateContext(context.Context, *CreateSourceContextRequest) (*CreateSourceContextResponse, error)
	RegisterContext(context.Context, *RegisterSourceContextRequest) (*RegisterSourceContextResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	mustEmbedUnimplementedCodemakerServiceServer()
}

// UnimplementedCodemakerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCodemakerServiceServer struct {
}

func (UnimplementedCodemakerServiceServer) AssistantCompletion(context.Context, *AssistantCompletionRequest) (*AssistantCompletionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssistantCompletion not implemented")
}
func (UnimplementedCodemakerServiceServer) AssistantCodeCompletion(context.Context, *AssistantCodeCompletionRequest) (*AssistantCodeCompletionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssistantCodeCompletion not implemented")
}
func (UnimplementedCodemakerServiceServer) Completion(context.Context, *CompletionRequest) (*CompletionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Completion not implemented")
}
func (UnimplementedCodemakerServiceServer) Process(context.Context, *ProcessRequest) (*ProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedCodemakerServiceServer) Predict(context.Context, *PredictRequest) (*PredictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedCodemakerServiceServer) DiscoverContext(context.Context, *DiscoverSourceContextRequest) (*DiscoverSourceContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscoverContext not implemented")
}
func (UnimplementedCodemakerServiceServer) CreateContext(context.Context, *CreateSourceContextRequest) (*CreateSourceContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContext not implemented")
}
func (UnimplementedCodemakerServiceServer) RegisterContext(context.Context, *RegisterSourceContextRequest) (*RegisterSourceContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterContext not implemented")
}
func (UnimplementedCodemakerServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedCodemakerServiceServer) mustEmbedUnimplementedCodemakerServiceServer() {}

// UnsafeCodemakerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodemakerServiceServer will
// result in compilation errors.
type UnsafeCodemakerServiceServer interface {
	mustEmbedUnimplementedCodemakerServiceServer()
}

func RegisterCodemakerServiceServer(s grpc.ServiceRegistrar, srv CodemakerServiceServer) {
	s.RegisterService(&CodemakerService_ServiceDesc, srv)
}

func _CodemakerService_AssistantCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssistantCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodemakerServiceServer).AssistantCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.codemaker.service.CodemakerService/AssistantCompletion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodemakerServiceServer).AssistantCompletion(ctx, req.(*AssistantCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodemakerService_AssistantCodeCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssistantCodeCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodemakerServiceServer).AssistantCodeCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.codemaker.service.CodemakerService/AssistantCodeCompletion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodemakerServiceServer).AssistantCodeCompletion(ctx, req.(*AssistantCodeCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodemakerService_Completion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodemakerServiceServer).Completion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.codemaker.service.CodemakerService/Completion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodemakerServiceServer).Completion(ctx, req.(*CompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodemakerService_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodemakerServiceServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.codemaker.service.CodemakerService/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodemakerServiceServer).Process(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodemakerService_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodemakerServiceServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.codemaker.service.CodemakerService/Predict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodemakerServiceServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodemakerService_DiscoverContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverSourceContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodemakerServiceServer).DiscoverContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.codemaker.service.CodemakerService/DiscoverContext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodemakerServiceServer).DiscoverContext(ctx, req.(*DiscoverSourceContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodemakerService_CreateContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSourceContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodemakerServiceServer).CreateContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.codemaker.service.CodemakerService/CreateContext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodemakerServiceServer).CreateContext(ctx, req.(*CreateSourceContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodemakerService_RegisterContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSourceContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodemakerServiceServer).RegisterContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.codemaker.service.CodemakerService/RegisterContext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodemakerServiceServer).RegisterContext(ctx, req.(*RegisterSourceContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodemakerService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodemakerServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.codemaker.service.CodemakerService/ListModels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodemakerServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CodemakerService_ServiceDesc is the grpc.ServiceDesc for CodemakerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CodemakerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.codemaker.service.CodemakerService",
	HandlerType: (*CodemakerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssistantCompletion",
			Handler:    _CodemakerService_AssistantCompletion_Handler,
		},
		{
			MethodName: "AssistantCodeCompletion",
			Handler:    _CodemakerService_AssistantCodeCompletion_Handler,
		},
		{
			MethodName: "Completion",
			Handler:    _CodemakerService_Completion_Handler,
		},
		{
			MethodName: "Process",
			Handler:    _CodemakerService_Process_Handler,
		},
		{
			MethodName: "Predict",
			Handler:    _CodemakerService_Predict_Handler,
		},
		{
			MethodName: "DiscoverContext",
			Handler:    _CodemakerService_DiscoverContext_Handler,
		},
		{
			MethodName: "CreateContext",
			Handler:    _CodemakerService_CreateContext_Handler,
		},
		{
			MethodName: "RegisterContext",
			Handler:    _CodemakerService_RegisterContext_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _CodemakerService_ListModels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/codemakerai.proto",
}
